modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/Terrails/Health-Overlay/issues"

[[mods]]
modId="healthoverlay"
version="${file.jarVersion}"
displayName="Health Overlay"

authors="Terrails"
description=''' A simple renderer for colored hearts '''